# Generated by Django 6.0.3 on 2026-04-03 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('current_stage', models.CharField(choices=[('context_intake', 'Context Intake'), ('pre_assessment', 'Pre-Assessment'), ('thinking_styles', 'Thinking Styles'), ('validation', 'Validation'), ('results', 'Results'), ('completed', 'Completed')], default='context_intake', max_length=20)),
                ('current_activity', models.IntegerField(default=0)),
                ('year_of_study', models.CharField(blank=True, default='', max_length=20)),
                ('prior_experience', models.CharField(blank=True, default='', max_length=20)),
                ('goal', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.FloatField(default=0)),
                ('frontend', models.FloatField(default=0)),
                ('devops', models.FloatField(default=0)),
                ('data_eng', models.FloatField(default=0)),
                ('ai_ml', models.FloatField(default=0)),
                ('cybersecurity', models.FloatField(default=0)),
                ('product_eng', models.FloatField(default=0)),
                ('validation_applied', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='assessment.assessmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('frontend_product', 'Frontend/Product'), ('backend_devops', 'Backend/DevOps'), ('data_ai', 'Data/AI'), ('cybersecurity', 'Cybersecurity')], max_length=20)),
                ('task_type', models.CharField(max_length=50)),
                ('response_data', models.JSONField(default=dict)),
                ('engagement_level', models.CharField(choices=[('strong', 'Strong Engagement'), ('good', 'Good Engagement'), ('partial', 'Partial/Mixed'), ('low', 'Low Engagement'), ('skipped', 'Skipped')], default='partial', max_length=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_responses', to='assessment.assessmentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.IntegerField(choices=[(1, 'Activity 1'), (2, 'Activity 2'), (3, 'Activity 3'), (4, 'Activity 4'), (5, 'Activity 5'), (6, 'Activity 6')])),
                ('response_data', models.JSONField(default=dict, help_text='Raw interaction data: order, positions, selections')),
                ('behavioral_signals', models.JSONField(default=dict, help_text='Extracted signals: timing, retries, patterns')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0, help_text='Total time spent on activity in milliseconds')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_responses', to='assessment.assessmentsession')),
            ],
            options={
                'ordering': ['activity_number'],
                'unique_together': {('session', 'activity_number')},
            },
        ),
        migrations.CreateModel(
            name='ThinkingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_key', models.CharField(choices=[('experience_shaper', 'The Experience Shaper'), ('problem_definer', 'The Problem Definer'), ('systems_thinker', 'The Systems Thinker'), ('reliability_keeper', 'The Reliability Keeper'), ('signal_seeker', 'The Signal Seeker'), ('hypothesis_tester', 'The Hypothesis Tester'), ('threat_anticipator', 'The Threat Anticipator'), ('trust_architect', 'The Trust Architect')], max_length=30)),
                ('confidence', models.FloatField(default=0, help_text='0-1 confidence score')),
                ('description', models.TextField(blank=True, default='', help_text='AI-generated explanation (placeholder)')),
                ('rank', models.IntegerField(default=0, help_text='1 = top match')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thinking_styles', to='assessment.assessmentsession')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('session', 'style_key')},
            },
        ),
    ]
