# Generated by Django 6.0.3 on 2026-07-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Which domain bubble triggered this chat', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('terminated', 'Terminated')], default='in_progress', max_length=15)),
                ('transcript', models.JSONField(default=list, help_text='Chat transcript as ordered message list')),
                ('roadmap_annotations', models.JSONField(default=list, help_text='Personalized roadmap annotation strings')),
                ('ai_turn_count', models.IntegerField(default=0)),
                ('user_turn_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dive_chats', to='assessment.assessmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'domain')},
            },
        ),
    ]
